Repository Act-It-FE/global-nomad, pull requests merged in 2025-08, with the labels that each got.

#182 ✨ feat: 내 체험 관리 페이지 추가
  src/app/mypage/activities/page.tsx
  src/app/mypage/reserve-status/page.tsx
  src/hooks/myActivities/useMyActivitiesQuery.ts
Labels: ✨ 기능 추가

#121 ✨Feat: OAuth API 구현
  .github/workflows/ci-cd-preview.yml
  env.d.ts
  src/api/feachProfile.ts
  src/api/kakao.ts
  src/api/oAuth.ts
  src/api/types/auth.ts
  src/app/login/callback/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signUp/page.tsx
  src/stores/userStore.ts
  src/types/Auth.ts
  src/utils/oauth/getRedirectUrl.ts
Labels: ✨ 기능 추가

#184 🐛 fix: 이미지가 세로로 길 경우 카드가 이상하게 보이는 현상 수정
  src/app/_components/CardColumn.tsx
Labels: 🐛 버그 수정, 🎨 UI/스타일

#188 ✨ feat : 내 알림 react query 훅 추가 및 기능 구현
  src/components/Gnb.tsx
  src/components/NotificationPanel.tsx
  src/hooks/myNotifications/queryKey.ts
  src/hooks/myNotifications/useMyNotifyMutate.ts
  src/hooks/myNotifications/useMyNotifyQuery.ts
  src/utils/parseNotificationContent.ts
Labels: ✨ 기능 추가

#195 ✨ feat: 리다이렉트URL수정
  src/app/login/callback/kakaocallback.tsx
  src/utils/oauth/getRedirectUrl.ts
Labels: ✨ 기능 추가, ♻️ 리팩토링

#193 ✨Feat:로그인, 회원가입 구현
  src/app/login/page.tsx
  src/app/signUp/page.tsx
Labels: ✨ 기능 추가

#197 🐛 fix: 이미지 업로드 API 함수 content-type header 지정
  src/api/activitiesApi.ts
  src/api/userApi.ts
Labels: 🐛 버그 수정

#187 ✨ feat: 커스텀 Date Input 추가
  src/components/Input.tsx
Labels: ✨ 기능 추가

#199 🐛 fix: mypage state 초기화 문제 수정
  src/app/mypage/layout.tsx
Labels: 🐛 버그 수정

#207 ✨ feat: ImageUploader component 구현
  src/app/mypage/add-activity/_components/ImageUploader.tsx
Labels: ✨ 기능 추가

#204 ✨feat : 체험예약 캘린더 구현
  src/app/[activityId]/_components/ActivitySummary.tsx
  src/app/[activityId]/_components/MobileReserveModal.tsx
  src/app/[activityId]/_components/ReserveCalender.tsx
  src/app/[activityId]/_components/TabletReserveModal.tsx
  src/app/[activityId]/_hooks/queries/useActivityDetail.ts
  src/app/[activityId]/_hooks/queries/useAvailableSchedule.ts
  src/app/[activityId]/page.tsx
Labels: ✨ 기능 추가

#208 ✨ feat: 내 정보 수정 페이지 구현 및 프로필 이미지 업로드 관련 수정
  src/app/mypage/info/page.tsx
  src/app/mypage/layout.tsx
  src/components/side-menu/Profile.tsx
  src/stores/userStore.ts
Labels: ✨ 기능 추가, 🎨 UI/스타일

#214 🐛 fix : 체험 상세 페이지 전체 테스트 및 수정사항 반영
  env.d.ts
  src/app/[activityId]/_components/ActivityDescription.tsx
  src/app/[activityId]/_components/ActivityDetailImage.tsx
  src/app/[activityId]/_components/ActivityReviews.tsx
  src/app/[activityId]/_components/ActivitySummary.tsx
  src/app/[activityId]/_components/FallbackImage.tsx
  src/app/[activityId]/_components/MobileReserveModal.tsx
  src/app/[activityId]/_components/ReserveCalender.tsx
  src/app/[activityId]/_components/TabletReserveModal.tsx
  src/app/[activityId]/_utils/activityDetailDates.ts
  src/app/[activityId]/_utils/getImageClass.ts
  src/app/[activityId]/layout.tsx
  src/app/[activityId]/page.tsx
  src/types/Auth.ts
Labels: 🐛 버그 수정, ✨ 기능 추가, 📁 폴더 구조 변경, 🎨 UI/스타일, ♻️ 리팩토링

#222 ✨ feat: favicon 및 메타 데이터 설정
  public/images/actit-logo.png
  src/app/favicon.ico
  src/app/layout.tsx
Labels: ✨ 기능 추가

#226 🐛 fix: 오류 모달+이동 처리
  src/app/login/callback/kakaocallback.tsx
Labels: 🐛 버그 수정

#227 🐛 fix: ActivityRegisterPayload schedule > schedules 이름 변경
  src/api/types/activities.ts
  src/app/mypage/(NoLayout)/add-activity/page.tsx
Labels: 🐛 버그 수정

#232 🐛 [bug/fix] : 체험등록시 입력한 날짜와 체험상세페이지에서 보여지는 날짜가 다른 버그 발생
  src/app/[activityId]/_components/MobileReserveModal.tsx
  src/app/[activityId]/_components/ReserveCalender.tsx
  src/app/[activityId]/_components/TabletReserveModal.tsx
  src/app/[activityId]/_utils/activityDetailDates.ts
Labels: 🐛 버그 수정

#233 🐛 fix: MyExperience 수정하기 경로 수정
  src/app/mypage/(Layout)/activities/_components/MyExperience.tsx
Labels: 🐛 버그 수정

#236 🚀 deploy: 실제 배포 (마지막이길)
  src/app/[activityId]/_components/MobileReserveModal.tsx
  src/app/[activityId]/_components/ReserveCalender.tsx
  src/app/[activityId]/_components/TabletReserveModal.tsx
  src/app/[activityId]/_utils/activityDetailDates.ts
  src/app/mypage/(Layout)/activities/_components/MyExperience.tsx
Labels: 🚀 프로젝트 배포

#243 ♻️ refactor: 체험 상세 페이지 layout 구조 및 스타일 개선
  src/app/[activityId]/layout.tsx
Labels: 🎨 UI/스타일, ♻️ 리팩토링
