Repository Act-It-FE/global-nomad, pull requests merged in 2025-07, with the labels that each got.

#13 ✨ chore: 허스키 설정 추가
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: 🔧 설정/빌드

#17 🐛 fix : 허스키 버그 수정
  package.json
Labels: 🐛 버그 수정

#14 ✨ feat: 버튼 컴포넌트 제작
  public/images/kakao-icon.png
  src/app/page.tsx
  src/components/button/Button.tsx
  src/constants/ButtonStyles.ts
  src/types/Button.ts
Labels: ✨ 기능 추가

#22 ✨ feat : tailwind css 합성 함수 구현
  package.json
  pnpm-lock.yaml
  src/app/page.tsx
  src/components/button/Button.tsx
  src/utils/.gitkeep
  src/utils/cn.ts
Labels: ✨ 기능 추가

#23 🔧 chore: eslint-plugin 추가
  package.json
  pnpm-lock.yaml
Labels: 🐛 버그 수정, 🔧 설정/빌드

#32 ✨ feat: useClickOutside hook 구현
  src/hooks/.gitkeep
  src/hooks/useClickOutside.ts
Labels: ✨ 기능 추가

#36 ✨ feat: Pagination 컴포넌트 구현
  src/app/globals.css
  src/app/page.tsx
  src/components/common/Pagination.tsx
Labels: ✨ 기능 추가, 🎨 UI/스타일

#43 ✨ feat: dropdown 컴포넌트 제작
  src/app/page.tsx
  src/components/common/DropDown.tsx
Labels: ✨ 기능 추가

#54 ✨feat: 알림 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/page.tsx
  src/components/common/Notification.tsx
Labels: ✨ 기능 추가

#63 ✨ feat: 테스트 페이지 생성
  src/app/mypage/layout.tsx
  src/app/mypage/test/page.tsx
Labels: ✨ 기능 추가

#68 ✨ feat: api.ts 기본 세팅
  .env.example
  .gitignore
  next-env.d.ts
  src/api/api.ts
  src/api/user/SignUp.ts
Labels: ✨ 기능 추가

#73 ✨ feat : 예약 내역 관련 api 구현
  src/libs/MyReservations.ts
  src/types/.gitkeep
  src/types/api/ReserveType.ts
Labels: ✨ 기능 추가

#87 🐛 fix: Gnb Icon 변경
  src/components/common/Gnb.tsx
Labels: 🐛 버그 수정

#79 ✨ feat: interceptor 토큰 작업
  src/api/api.ts
  src/components/common/Modal/contents/WarningContent.tsx
Labels: ✨ 기능 추가, ♻️ 리팩토링

#95 🔥 fix: api파일위치 변경
  src/libs/api.ts
  src/libs/user/SignUp.ts
Labels: 📁 폴더 구조 변경

#92 🐛 fix: env.d.ts파일 생성
  env.d.ts
  next-env.d.ts
  tsconfig.json
Labels: 🐛 버그 수정

#112 📁 chore : 공통 컴포넌트 파일들 위치 이동
  src/app/layout.tsx
  src/app/mypage/layout.tsx
  src/app/page.tsx
  src/components/Button.tsx
  src/components/Card.tsx
  src/components/DropDown.tsx
  src/components/Footer.tsx
  src/components/Gnb.tsx
  src/components/Icon.tsx
  src/components/ImageUploader.tsx
  src/components/Input.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/contents/OnlyTextContent.tsx
  src/components/Modal/contents/ReviewContent.tsx
  src/components/Modal/contents/WarningContent.tsx
  src/components/NotificationPanel.tsx
  src/components/Pagination.tsx
  src/components/side-menu/Menu.tsx
  src/components/side-menu/Profile.tsx
  src/components/side-menu/SideMenu.tsx
  src/constants/Modal.ts
Labels: 📁 폴더 구조 변경

#116 ✨ feat: userApi 구현 및 타입 정의
  src/api/types/auth.ts
  src/api/userApi.ts
  src/components/side-menu/Profile.tsx
  src/libs/upload.ts
  src/libs/user/SignUp.ts
Labels: ✨ 기능 추가

#122 ✨ feat : 예약 내역 api 연결 및 query 훅 설정과 에러 메시지 커스텀 훅 추가
  src/app/mypage/reserves/page.tsx
  src/hooks/reservations/queryKeys.ts
  src/hooks/reservations/useMyReservationsMutate.ts
  src/hooks/reservations/useMyReservationsQuery.ts
  src/utils/getErrorMessage.ts
Labels: ✨ 기능 추가

#124 ✨ feat : 예약 내역 카드 구현 및 토스트 메시지 추가
  src/app/mypage/reserves/_components/CancelReservationButton.tsx
  src/app/mypage/reserves/_components/ReservesBottom.tsx
  src/app/mypage/reserves/_components/ReservesCard.tsx
  src/app/mypage/reserves/_components/ReservesHeader.tsx
  src/app/mypage/reserves/_components/ReviewReservationButton.tsx
  src/app/mypage/reserves/page.tsx
  src/components/Modal/contents/WarningContent.tsx
  src/components/Toast.tsx
Labels: ✨ 기능 추가

#81 ✨ feat Activities api 타입 설정 및 함수 구현
  src/api/types/Activities.ts
  src/components/NotificationPanel.tsx
  src/libs/activitiesDetail.ts
Labels: ✨ 기능 추가

#123 ✨ feat: Search 컴포넌트 구현
  src/app/_components/Search.tsx
Labels: ✨ 기능 추가

#131 ✨ feat : 예약 현황 페이지 API 연결 및 Query 훅 구현
  src/api/types/myActivities.ts
  src/app/mypage/reserve-status/page.tsx
  src/hooks/reserve-status/queryKey.ts
  src/hooks/reserve-status/useMyActReservationMutate.ts
  src/hooks/reserve-status/useMyActivitiesQuery.ts
Labels: ✨ 기능 추가

#139 ✨feat : 카카오 지도 컴포넌트 구현
  global.d.ts
  src/app/[activityId]/_components/LoadKakaoMap.tsx
  src/app/[activityId]/_components/RenderKakaoMap.tsx
  src/app/[activityId]/layout.tsx
  src/app/[activityId]/page.tsx
  svg.d.ts
  tsconfig.json
Labels: ✨ 기능 추가

#138 ✨ feat: TopBanner 컴포넌트 구현
  src/app/_components/TopBanner.tsx
Labels: ✨ 기능 추가

#136 📁 chore: Activities api 파일 이동
  src/api/activitiesApi.ts
  src/api/types/activities.ts
  src/app/[activityId]/page.tsx
Labels: ✨ 기능 추가, 📁 폴더 구조 변경, ♻️ 리팩토링

#147 ✨ feat: Input textarea scrollbar 디자인
  src/components/Input.tsx
Labels: ✨ 기능 추가, 🎨 UI/스타일, ♻️ 리팩토링

#151 🐛 fix: Input type='dropdown' 오류 수정 및 스타일/prop 추가
  src/components/Input.tsx
Labels: 🐛 버그 수정, ✨ 기능 추가, 🎨 UI/스타일, ♻️ 리팩토링

#154 ✨ feat: 모든 체험 컴포넌트 AllActivities 구현
  src/api/types/activities.ts
  src/app/_components/ActivityList.tsx
  src/app/_components/AllActivities.tsx
  src/app/_components/CardColumn.tsx
  src/app/_components/CategoryBar.tsx
  src/app/_components/SortDropdown.tsx
  src/app/page.tsx
  src/hooks/activities/useActivitiesQuery.ts
Labels: ✨ 기능 추가

#144 ✨ feat: 내 체험 선택 드롭다운 컴포넌트 구현
  src/app/mypage/reserve-status/_components/MyActListDropDown.tsx
  src/app/mypage/reserve-status/page.tsx
Labels: ✨ 기능 추가

#155 ✨ feat : 달력 UI 컴포넌트 구현
  src/app/mypage/reserve-status/_components/calendar/Calendar.tsx
  src/app/mypage/reserve-status/_components/calendar/CalendarGrid.tsx
  src/app/mypage/reserve-status/_components/calendar/CalendarHeader.tsx
  src/app/mypage/reserve-status/_components/calendar/DayCell.tsx
  src/app/mypage/reserve-status/page.tsx
  src/app/mypage/reserves/utils/hooks/useCalendar.ts
  src/app/mypage/reserves/utils/index.ts
  src/app/mypage/reserves/utils/types/index.ts
  src/hooks/myActivities/queryKey.ts
  src/hooks/myActivities/useMyActReservationMutate.ts
  src/hooks/myActivities/useMyActivitiesQuery.ts
  src/stores/.gitkeep
  src/stores/calendarStore.ts
  src/utils/dateUtils.ts
Labels: ✨ 기능 추가

#160 📁 chore : 캘린더 utils 폴더 이동
  src/app/mypage/reserve-status/_components/calendar/CalendarHeader.tsx
  src/app/mypage/reserve-status/_components/calendar/utils/hooks/useCalendar.ts
  src/app/mypage/reserve-status/_components/calendar/utils/index.ts
  src/app/mypage/reserve-status/_components/calendar/utils/types/index.ts
Labels: 📁 폴더 구조 변경

#156 ✨feat : 체험상세페이지의 체험설명 컴포넌트 구현
  src/app/[activityId]/_components/ActivityDescription.tsx
  src/app/[activityId]/page.tsx
  src/hooks/activity-details/useActivityDescription.ts
  src/utils/getImageClass.ts
Labels: ✨ 기능 추가, 🎨 UI/스타일

#161 ✨ feat: myActivities 내 체험 관련 Mutation 구현
  src/hooks/myActivities/queryKey.ts
  src/hooks/myActivities/useMyActReservationMutate.ts
  src/hooks/myActivities/useMyActivitiesQuery.ts
Labels: ✨ 기능 추가, ♻️ 리팩토링

#162 ✨ feat: 인기 체험 섹션 구현
  src/app/_components/CardColumn.tsx
  src/app/_components/PopularActivities.tsx
  src/app/_components/PopularActivitiesCarousel.tsx
  src/app/page.tsx
Labels: ✨ 기능 추가, 🎨 UI/스타일

#167 🐛 fix: 모달 버튼 수정
  src/app/signup/page.tsx
  src/components/Modal/contents/WarningContent.tsx
  src/types/Modal.ts
Labels: 🐛 버그 수정, ♻️ 리팩토링

#171 ✨ feat : 달력 데이터 연동 및 상호작용 구현
  src/app/mypage/reserve-status/_components/MyActListDropDown.tsx
  src/app/mypage/reserve-status/_components/ReservationDropDown.tsx
  src/app/mypage/reserve-status/_components/ReservationList.tsx
  src/app/mypage/reserve-status/_components/ReservationModal.tsx
  src/app/mypage/reserve-status/_components/ReservationModalHeader.tsx
  src/app/mypage/reserve-status/_components/calendar/Calendar.tsx
  src/app/mypage/reserve-status/_components/calendar/CalendarGrid.tsx
  src/app/mypage/reserve-status/_components/calendar/DayCell.tsx
  src/app/mypage/reserve-status/_utils/hooks/useCalendar.ts
  src/app/mypage/reserve-status/_utils/index.ts
  src/app/mypage/reserve-status/_utils/reservationUtils.ts
  src/app/mypage/reserve-status/_utils/types/index.ts
  src/app/mypage/reserve-status/page.tsx
  src/components/Input.tsx
  src/hooks/myActivities/useMyActivitiesQuery.ts
  src/stores/calendarStore.ts
  src/utils/dateUtils.ts
Labels: ✨ 기능 추가

#180 ✨ feat: 예약 내역 페이지 로딩 구현
  src/app/mypage/reserves/page.tsx
Labels: ✨ 기능 추가
